name: YT 2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12 * * *'


jobs:
  capture_screenshots:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        usersname:
          - "usernames1"
          - "usernames2"
          - "usernames3"
          - "usernames4"
          - "usernames5"
          - "usernames6"
          - "usernames7"
          - "usernames8"
          - "usernames9"
          - "usernames10"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'
           
      - name: Print date and time
        run: echo "Workflow started at $(TZ='Asia/Ho_Chi_Minh' date)"
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update and upgrade packages
        run: sudo apt-get update && sudo apt-get upgrade -y
        
      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg
        
      # - name: Install OpenVPN and Connect to VPN
      #   run:  |
      #       sudo apt install -y openvpn openvpn-systemd-resolved
            
      # - name: Connect to VPN
      #   uses: "kota65535/github-openvpn-connect-action@v2"
      #   with:
      #     config_file: newuser.ovpn
      #     # username: ${{ secrets.OVPN_USERNAME }}
      #     # password: ''
      #     # client_key: ${{ secrets.OVPN_CLIENT_KEY }}
      #     # tls_auth_key: ${{ secrets.OVPN_TLS_AUTH_KEY }}
      
      - name: Create user folders
        run: mkdir -p $GITHUB_WORKSPACE/${{ matrix.usersname }}

      - name: Run Selenium script
        run: python main3.py -username ${{ matrix.usersname }}
      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.usersname }}
          path: ${{ matrix.usersname }}
